#ifndef TENSORFLOW_LITE_MICRO_EXAMPLES_INPUT_IMAGES_H_
#define TENSORFLOW_LITE_MICRO_EXAMPLES_INPUT_IMAGES_H_

extern const unsigned char s_imgs[];

#endif  // TENSORFLOW_LITE_MICRO_EXAMPLES_HELLO_WORLD_INPUT_IMAGES_H_
